apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc  # Usa el mismo cluster donde está Argo CD
    namespace: argo-demo  # El namespace donde se desplegará la app
  source:
    repoURL: https://github.com/tu-usuario/tu-repositorio.git  # URL de tu repo
    targetRevision: HEAD  # Rama o revisión específica (ej. main, v1.0.0)
    path: .  # Ruta dentro del repo donde están los manifiestos
  project: default
  syncPolicy:
    automated:  # Habilita la sincronización automática
      selfHeal: true  # Revierte cambios manuales en el cluster
    syncOptions:
    - CreateNamespace=true  # Crea el namespace si no existe
